spring:
  application:
    name: datos-dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ecommerce
    username: sa
    password:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql # script de carga de datos
  h2:
    console:
      enabled: true           # Habilita la consola web de H2
      path: /h2-console      # Ruta para acceder a la consola (http://localhost:8080/h2-console)
  jpa:
    defer-datasource-initialization: true # config para que primero se creen las tablas y luego carguen los scripts
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create  # create, create-drop, validate, update
    show-sql: true           # Muestra las consultas SQL en la consola
